# Generated by Django 5.2.7 on 2025-10-26 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id_proyecto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_entrega', models.DateField()),
                ('id_empleado', models.IntegerField()),
                ('id_campaña', models.IntegerField()),
            ],
        ),
    ]
